### ISSUE TITLE
Docs: Mutation Example

### ISSUE THREAD

**Issue by rattrayalex** [graphql-python/django-graphene-example#2]
Hi there, 

This looks amazing! Thanks so much for such a simple example of what looks like a terrific library. It would be awesome to see an example with mutations, if for no other reason than to assure readers that they work :-)

**Comment by syrusakbary** [comment]
Hi @rattrayalex, I didn't implement mutations in the swapi example because it may "overload" the data in the database with non-standard instances (like strange Characters or Spaceships created by people).

There is already an example of using mutations in `graphene` with Django:
https://github.com/graphql-python/graphene/tree/master/examples/starwars_django
(With [tests included](https://github.com/graphql-python/graphene/blob/master/examples/starwars_django/tests/test_mutation.py))

I could solve this issue by:
- Create a custom Hero model and let the people create their own heroes through mutations
- Place a link in the SWAPI README to the example of how to use mutations.

Let me know what you think could be better!

**Comment by syrusakbary** [comment]
@rattrayalex waiting for your response! :wink:

**Comment by rattrayalex** [comment]
Gotcha, totally makes sense!

I do think it would be pretty cool to see how it works, and both your suggestions sound great to me. I assume you could run a batch job (hourly, maybe?) to delete all heroes so things don't get too crazy. Unless you're getting huge amounts of traffic and even that would be too much?

Cheers!

**Comment by syrusakbary** [comment]
Hi @rattrayalex,

I've updated the schema adding the `createHero` mutation.
You can execute [the query](http://swapi.graphene-python.org/graphiql?query=mutation%20MyMutation%20%7B%0A%20%20createHero%28input%3A%7BclientMutationId%3A%22a%22%2C%20name%3A%22Peter%22%2C%20homeworldId%3A%221%22%7D%29%20%7B%0A%20%20%20%20hero%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20homeworld%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20ok%0A%20%20%7D%0A%7D):

``` graphql
mutation MyMutation {
  createHero(input:{clientMutationId:"a", name:"Peter", homeworldId:"1"}) {
    hero {
      id
      name
      homeworld {
        id
        name
      }
    }
    ok
  }
}
```

**Each time you execute it a new hero will be created**

Also, you can query the heroes by:

``` graphql
query {
  allHeroes {
    edges {
      node {
        name
        homeworld {
          name
        }
      }
    }
  }
}
```

Hope you find it useful! :wink:

**Comment by rattrayalex** [comment]
Wow, amazing - thank you so much! Can't wait to give it a try!
